### ISSUE TITLE
11 MB Binary?

### ISSUE THREAD

**Issue by camAtGitHub** [Sett17/turboCommit#20]
Hi,

I compiled turbocommit and noticed the binary is 11 MB (Megabytes). 
Am I doing something wrong for it to be that size?

Thanks

**Comment by Sett17** [comment]
You are not doing anything wrong. By default, everything is statically linked. There are guides like [min-sized-rust](https://github.com/johnthagen/min-sized-rust) to address the size of rust binaries.

If the 11Mb is a concern to you, feel free to fork this and adapt it for a smaller binary size and consider making a PR if you do so.
