### ISSUE TITLE
Flickering on animated text

### ISSUE THREAD

**Issue by 0atman** [Sett17/turboCommit#6]
Thank you for making this awesome utility! 

Is the animated text necessary? I don't think it was animated in a previous version.

For me, it's got no upside, it's
1. Slower, and
2. Flickers inside my terminal multiplexer (zellij)

I updated today.

```sh
turbocommit --version
turbocommit version 0.8.3
```

**Comment by Sett17** [comment]
It shouldn't really be any slower, as it is just receiving each token in a stream from the API.
But it does make sense to add a CLI option and default config to just print the messages when they are done.

Does it only flicker when receiving the messages, or also when waiting with the spinning clock?

**Comment by Sett17** [comment]
@0atman when/if possible, please see i #8 fixes your issue
